import { test, expect, type Page, type BrowserContext } from '@playwright/test';

// ============================================================================
// ตั้งค่า Email & Password สำหรับเข้า Strapi Admin (แก้ให้ตรงกับของคุณ)
// ============================================================================
const ADMIN_EMAIL = 'ujubptub@gmail.com';
const ADMIN_PASSWORD = 'Jaa02488';
const BASE_URL = 'http://localhost:1337/admin';

test.describe('Strapi Admin User Journeys', () => {
  // รันแบบเรียงลำดับต่อเนื่องกัน เพราะต้องล็อคอินก่อนแล้วค่อยสร้าง แก้ ลบ
  test.describe.configure({ mode: 'serial' });

  let page: Page;
  let context: BrowserContext;

  test.beforeAll(async ({ browser }) => {
    // สร้าง context ใหม่แบบ clean (ไม่มี cookie เก่า) เพื่อให้ login page โผล่ถูกต้อง
    context = await browser.newContext();
    page = await context.newPage();
  });

  test.afterAll(async () => {
    await context.close();
  });

  // ============================================================
  // Journey 1: Login เข้า Strapi Admin
  // ============================================================
  test('Journey 1: Login to Strapi Admin', async () => {
    // ไปที่หน้า login โดยตรง (ไม่ต้อง redirect จาก /admin)
    await page.goto(`${BASE_URL}/auth/login`, { waitUntil: 'domcontentloaded' });

    // รอให้ React SPA โหลดและ render form (Strapi 5 ใช้ React ใช้เวลานิดหน่อย)
    await page.waitForSelector('input[name="email"]', { timeout: 30000 });

    // กรอกอีเมลและรหัสผ่าน
    await page.fill('input[name="email"]', ADMIN_EMAIL);
    await page.fill('input[name="password"]', ADMIN_PASSWORD);

    // กดปุ่ม Login
    await page.click('button[type="submit"]');

    // รอ redirect ไปหน้า dashboard หลัง login สำเร็จ
    await page.waitForURL(/.*\/admin(?!\/auth)/, { timeout: 30000 });

    // รอให้เมนูซ้ายมือโหลดเสร็จ (Content Manager)
    await page.waitForSelector('nav', { timeout: 20000 }).catch(() => { });
  });

  // ============================================================
  // Journey 2: เข้าไปสร้างข้อมูลใน Content Manager (เช่น สร้าง Contact)
  // ============================================================
  test('Journey 2: Create a new Contact entry', async () => {
    // ไปที่หน้า Content Manager ของ Contact
    // URL format: /admin/content-manager/collection-types/api::contact.contact
    await page.goto(`${BASE_URL}/content-manager/collection-types/api::contact.contact`);

    // รอให้หน้าต่างโหลดเสร็จจริงๆ (รอ Network นิ่ง) จะได้ชัวร์ว่า Modal โหลดเสร็จถ้ามันจะเด้ง
    await page.waitForLoadState('networkidle');

    // ดักจับและปิด Popup แนะนำวิธีใช้ (Onboarding/Tour) หรือ Welcome Trial Modal ที่อาจจะโผล่มาช้าและบังหน้าจอ
    try {
      const skipButton = page.getByRole('button', { name: 'Skip' });
      const trialButton = page.getByRole('button', { name: /start exploring|close/i });

      // ตรวจสอบและรอตัวใดตัวหนึ่งโผล่ขึ้นมาด้วย locator.or()
      await skipButton.or(trialButton).waitFor({ state: 'visible', timeout: 5000 });

      if (await skipButton.isVisible()) {
        await skipButton.click();
        await skipButton.waitFor({ state: 'hidden' }).catch(() => { });
      }

      if (await trialButton.first().isVisible()) {
        await trialButton.first().click();
        await trialButton.first().waitFor({ state: 'hidden' }).catch(() => { });
      }
    } catch (e) {
      // ไม่มี popup โผล่มาเลยภายใน 5 วินาที หรือเกิดความผิดพลาด ให้รันต่อไป
    }

    // กดปุ่ม "Create new entry"
    const createButton = page.getByRole('main').getByRole('link', { name: /create new entry/i }).first();
    await createButton.click();

    // รอให้หน้าต่างฟอร์มโหลด (URL เปลี่ยนเป็น /create)
    await page.waitForURL(/.*\/create/);

    // สมมติว่าใน Contact มีฟิลด์ "formName", "formEmail", "formMessage" (เปลี่ยนตามโครงสร้างจริงของคุณ)
    // ตรงนี้เราใส่ dummy data ไว้ก่อน หากโครงสร้างฟิลด์ชื่ออื่น ให้เปลี่ยนชื่อ `name="..."` ให้ตรง
    try {
      await page.fill('input[name="formName"]', 'Playwright Test User');
      await page.fill('input[name="formEmail"]', 'test@playwright.com');
      await page.fill('input[name="formMessage"]', 'This is a test message generated by Playwright e2e test.');
    } catch (e) {
      console.log('Fields might have different names, skipping fill for safety.');
    }

    // กดปุ่ม Save
    await page.getByRole('button', { name: /save/i }).click();

    // รอให้บันทึกเสร็จ Strapi จะเปลี่ยน URL จาก /create ไปเป็น /1 (หรือเลข ID ของข้อมูล)
    // ตรงนี้สำคัญมาก ถ้ารีบไป Journey 3 ก่อนที่หน้าเว็บจะโหลดเสร็จ ข้อมูลที่พิมพ์ไปจะหายหมด
    await page.waitForURL(url => !url.toString().includes('/create'), { timeout: 15000 });
  });

  // ============================================================
  // Journey 3: แก้ไขข้อมูล (Edit Content)
  // ============================================================
  test('Journey 3: Edit the existing entry', async () => {
    // ตอนนี้เราน่าจะยังอยู่ที่หน้าแก้ไข (จาก Journey 2)
    // เปลี่ยนข้อมูลในช่อง formName เพื่อให้ระบบเปิดปุ่ม Save
    await page.fill('input[name="formName"]', 'Playwright Test User (EDITED)');

    // กดปุ่ม Save อีกครั้ง
    await page.getByRole('button', { name: /save/i }).click();

    // รอข้อความ Saved แจ้งเตือนมุมขวาบน หรือรอให้ปุ่ม save หยุดโหลด
    await page.waitForTimeout(2000);
  });

  // ============================================================
  // Journey 4: ลบข้อมูล (Delete Content) & Logout
  // ============================================================
  test('Journey 4: Delete entry and Logout', async () => {
    // กลับไปหน้ารวม (List view)
    await page.goto(`${BASE_URL}/content-manager/collection-types/api::contact.contact`);

    // รอจนตารางข้อมูลขึ้น
    await page.waitForSelector('table');

    // คลิก Checkbox ตัวแรก (ข้ามอันแรกสุดที่เป็นของ Header) เพื่อให้แถบ Bulk action โผล่
    const firstCheckbox = page.getByRole('checkbox').nth(1);

    if (await firstCheckbox.isVisible()) {
      await firstCheckbox.click({ force: true });

      // พอกด checkbox จะมีปุ่ม Delete โผล่ขึ้นมาข้างบนตาราง
      await page.getByRole('button', { name: /delete/i }).click();

      // จะมี Modal ถามยืนยันการลบ
      await page.getByRole('button', { name: /confirm/i }).click();

      // รอจนกว่าจะลบเสร็จ
      await page.waitForTimeout(2000);
    }

    // ทำการ Logout
    // กดที่ Profile avatar มุมล่างซ้าย
    // ใช้ .first() เพื่อป้องกันกรณีที่ไป match โดนปุ่มเลือกภาษา
    const profileButton = page.locator('button:has-text("JA"), button:has-text("PH")').first();
    if (await profileButton.isVisible()) {
      await profileButton.click();
      // เมนูของ Strapi จะเขียนว่า "Log out" (มีเว้นวรรค)
      await page.getByRole('menuitem', { name: /log out|logout/i }).click();
    }
  });
});
