import { test, expect } from '@playwright/test';

// ============================================================================
// ตั้งค่า Email & Password สำหรับเข้า Strapi Admin (แก้ให้ตรงกับของคุณ)
// ============================================================================
const ADMIN_EMAIL = 'jaahaha10@gmail.com';
const ADMIN_PASSWORD = 'Jaa02488';
const BASE_URL = 'http://localhost:1337/admin';

test.describe('Strapi Admin User Journeys', () => {
  // รันแบบเรียงลำดับต่อเนื่องกัน เพราะต้องล็อคอินก่อนแล้วค่อยสร้าง แก้ ลบ
  test.describe.configure({ mode: 'serial' });

  let page;

  test.beforeAll(async ({ browser }) => {
    // สร้าง page ใหม่ที่จะใช้ร่วมกันตลอดทั้ง 4 journeys
    page = await browser.newPage();
  });

  test.afterAll(async () => {
    await page.close();
  });

  // ============================================================
  // Journey 1: Login เข้า Strapi Admin
  // ============================================================
  test('Journey 1: Login to Strapi Admin', async () => {
    await page.goto(BASE_URL);

    // รอจนกว่าฟอร์ม login จะโผล่
    await page.waitForSelector('form');

    // กรอกอีเมลและรหัสผ่าน
    await page.fill('input[name="email"]', ADMIN_EMAIL);
    await page.fill('input[name="password"]', ADMIN_PASSWORD);

    // กดปุ่ม Login
    await page.click('button[type="submit"]');

    // ตรวจสอบว่าเข้าหน้า Dashboard สำเร็จโดยดูจาก URL หรือตัวอักษรบนหน้า
    await expect(page).toHaveURL(/.*\/admin/);

    // รอให้เมนูซ้ายมือโหลดเสร็จ (Content Manager)
    await page.waitForSelector('nav[aria-label="Content-type"]', { timeout: 15000 }).catch(() => { });
  });

  // ============================================================
  // Journey 2: เข้าไปสร้างข้อมูลใน Content Manager (เช่น สร้าง Contact)
  // ============================================================
  test('Journey 2: Create a new Contact entry', async () => {
    // ไปที่หน้า Content Manager ของ Contact
    // URL format: /admin/content-manager/collection-types/api::contact.contact
    await page.goto(`${BASE_URL}/content-manager/collection-types/api::contact.contact`);

    // รอให้หน้าต่างโหลดเสร็จจริงๆ (รอ Network นิ่ง) จะได้ชัวร์ว่า Modal โหลดเสร็จถ้ามันจะเด้ง
    await page.waitForLoadState('networkidle');

    // ดักจับและปิด Popup แนะนำวิธีใช้ (Onboarding/Tour) ที่อาจจะโผล่มาช้า
    try {
      const skipButton = page.getByRole('button', { name: 'Skip' });
      await skipButton.waitFor({ state: 'visible', timeout: 3000 }); // รอสูงสุด 3 วิ
      await skipButton.click();
      await skipButton.waitFor({ state: 'hidden' });
    } catch (e) {
      // ถ้าไม่โผล่มาใน 3 วิ ก็ถือว่าไม่มี popup
    }

    // กดปุ่ม "Create new entry"
    const createButton = page.getByRole('main').getByRole('link', { name: /create new entry/i }).first();
    await createButton.click();

    // รอให้หน้าต่างฟอร์มโหลด (URL เปลี่ยนเป็น /create)
    await page.waitForURL(/.*\/create/);

    // สมมติว่าใน Contact มีฟิลด์ "formName", "formEmail", "formMessage" (เปลี่ยนตามโครงสร้างจริงของคุณ)
    // ตรงนี้เราใส่ dummy data ไว้ก่อน หากโครงสร้างฟิลด์ชื่ออื่น ให้เปลี่ยนชื่อ `name="..."` ให้ตรง
    try {
      await page.fill('input[name="formName"]', 'Playwright Test User');
      await page.fill('input[name="formEmail"]', 'test@playwright.com');
      await page.fill('input[name="formMessage"]', 'This is a test message generated by Playwright e2e test.');
    } catch (e) {
      console.log('Fields might have different names, skipping fill for safety.');
    }

    // กดปุ่ม Save
    await page.getByRole('button', { name: /save/i }).click();

    // รอให้บันทึกเสร็จ Strapi จะเปลี่ยน URL จาก /create ไปเป็น /1 (หรือเลข ID ของข้อมูล)
    // ตรงนี้สำคัญมาก ถ้ารีบไป Journey 3 ก่อนที่หน้าเว็บจะโหลดเสร็จ ข้อมูลที่พิมพ์ไปจะหายหมด
    await page.waitForURL(url => !url.toString().includes('/create'), { timeout: 15000 });
  });

  // ============================================================
  // Journey 3: แก้ไขข้อมูล (Edit Content)
  // ============================================================
  test('Journey 3: Edit the existing entry', async () => {
    // ตอนนี้เราน่าจะยังอยู่ที่หน้าแก้ไข (จาก Journey 2)
    // เปลี่ยนข้อมูลในช่อง formName เพื่อให้ระบบเปิดปุ่ม Save
    await page.fill('input[name="formName"]', 'Playwright Test User (EDITED)');

    // กดปุ่ม Save อีกครั้ง
    await page.getByRole('button', { name: /save/i }).click();

    // รอข้อความ Saved แจ้งเตือนมุมขวาบน หรือรอให้ปุ่ม save หยุดโหลด
    await page.waitForTimeout(2000);
  });

  // ============================================================
  // Journey 4: ลบข้อมูล (Delete Content) & Logout
  // ============================================================
  test('Journey 4: Delete entry and Logout', async () => {
    // กลับไปหน้ารวม (List view)
    await page.goto(`${BASE_URL}/content-manager/collection-types/api::contact.contact`);

    // รอจนตารางข้อมูลขึ้น
    await page.waitForSelector('table');

    // คลิก Checkbox ตัวแรก (ข้ามอันแรกสุดที่เป็นของ Header) เพื่อให้แถบ Bulk action โผล่
    const firstCheckbox = page.getByRole('checkbox').nth(1);
    
    if (await firstCheckbox.isVisible()) {
      await firstCheckbox.click({ force: true });
      
      // พอกด checkbox จะมีปุ่ม Delete โผล่ขึ้นมาข้างบนตาราง
      await page.getByRole('button', { name: /delete/i }).click();
      
      // จะมี Modal ถามยืนยันการลบ
      await page.getByRole('button', { name: /confirm/i }).click();
      
      // รอจนกว่าจะลบเสร็จ
      await page.waitForTimeout(2000);
    }

    // ทำการ Logout
    // กดที่ Profile avatar มุมล่างซ้าย
    // ใช้ .first() เพื่อป้องกันกรณีที่ไป match โดนปุ่มเลือกภาษา
    const profileButton = page.locator('button:has-text("JA"), button:has-text("PH")').first();
    if (await profileButton.isVisible()) {
      await profileButton.click();
      // เมนูของ Strapi จะเขียนว่า "Log out" (มีเว้นวรรค)
      await page.getByRole('menuitem', { name: /log out|logout/i }).click();
    }
  });
});
